// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBasoMpJ4cFDXin24vk418qXPAtG4l-hYg',
    appId: '1:776981450339:web:737855c967540792177256',
    messagingSenderId: '776981450339',
    projectId: 'ifgf-purwokerto',
    authDomain: 'ifgf-purwokerto.firebaseapp.com',
    storageBucket: 'ifgf-purwokerto.firebasestorage.app',
    measurementId: 'G-M564Z5MPM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_JKT84E-DAtM44eu4Mn9w_4DWfAyHL4',
    appId: '1:776981450339:android:e614775145d80361177256',
    messagingSenderId: '776981450339',
    projectId: 'ifgf-purwokerto',
    storageBucket: 'ifgf-purwokerto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUrGMWEa-0o3URDqJs3lPE8ncAVJoNx5I',
    appId: '1:776981450339:ios:1423e599251f6758177256',
    messagingSenderId: '776981450339',
    projectId: 'ifgf-purwokerto',
    storageBucket: 'ifgf-purwokerto.firebasestorage.app',
    iosBundleId: 'com.swu.ifgfapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUrGMWEa-0o3URDqJs3lPE8ncAVJoNx5I',
    appId: '1:776981450339:ios:b9fba7d9b1f74f6f177256',
    messagingSenderId: '776981450339',
    projectId: 'ifgf-purwokerto',
    storageBucket: 'ifgf-purwokerto.firebasestorage.app',
    iosBundleId: 'com.example.ifgfApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBasoMpJ4cFDXin24vk418qXPAtG4l-hYg',
    appId: '1:776981450339:web:7ce118f063dac540177256',
    messagingSenderId: '776981450339',
    projectId: 'ifgf-purwokerto',
    authDomain: 'ifgf-purwokerto.firebaseapp.com',
    storageBucket: 'ifgf-purwokerto.firebasestorage.app',
    measurementId: 'G-Y7DYE7J463',
  );

}